# -*- coding: utf-8 -*-
"""BRB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PdXNUarGM4hlirnKTlQ0XCxO13Yh1k6
"""

import numpy as np
from fairness_profile import functionFairnessProfile_cvx


def functionBRBalgorithm_cvx(H,
                             Pmax,
                             sigma2=1,
                             tolerance=1e-3,
                             max_iter=100):
    """
    Branch Reduce and Bound Algorithm
    """

    K = H.shape[1]

    fairness_profile = np.ones(K) / K
    rate_start = np.zeros(K)

    lower_bound = 0
    upper_bound = 100

    best_rate = 0
    best_W = None

    for iteration in range(max_iter):

        candidate_rate, W = functionFairnessProfile_cvx(
            H,
            fairness_profile,
            rate_start,
            Pmax,
            sigma2,
            tolerance
        )

        if candidate_rate > best_rate:
            best_rate = candidate_rate
            best_W = W

        if abs(upper_bound - lower_bound) < tolerance:
            break

        lower_bound = best_rate

    return best_rate, best_W