# -*- coding: utf-8 -*-
"""FairnessProfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQ9eAmc9uSudUA5ZKxtfB2JJVKmFfajZ
"""

import numpy as np
from feasibility_problem import functionFeasibilityProblem_cvx


def functionFairnessProfile_cvx(H,
                                 fairness_profile,
                                 rate_start,
                                 Pmax,
                                 sigma2=1,
                                 tolerance=1e-3,
                                 max_iter=50):
    """
    Fairness profile optimization using bisection
    """

    K = H.shape[1]

    lower = 0
    upper = 100

    best_rate = 0
    best_W = None

    for _ in range(max_iter):

        candidate = (lower + upper) / 2

        rates = rate_start + fairness_profile * candidate

        gamma = 2 ** rates - 1

        feasible, W = functionFeasibilityProblem_cvx(
            H,
            gamma,
            Pmax,
            sigma2
        )

        if feasible:
            lower = candidate
            best_rate = candidate
            best_W = W
        else:
            upper = candidate

        if abs(upper - lower) < tolerance:
            break

    return best_rate, best_W