# -*- coding: utf-8 -*-
"""Feasibility

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHMjoJ-7mNQJ2-SM6J1bsdDKjjZ_GPO4
"""

import numpy as np
import cvxpy as cp


def functionFeasibilityProblem_cvx(H, gamma, Pmax, sigma2=1):
    """
    Solve SINR feasibility problem using CVXPY

    Parameters
    ----------
    H : ndarray
        Channel matrix (N x K)
    gamma : ndarray
        SINR targets
    Pmax : float
        Maximum transmit power
    sigma2 : float
        Noise variance
    """

    N, K = H.shape

    W = cp.Variable((N, K), complex=True)

    constraints = []

    for k in range(K):

        hk = H[:, k]

        signal = cp.real(hk.conj().T @ W[:, k])

        interference_terms = []

        for i in range(K):
            if i != k:
                interference_terms.append(hk.conj().T @ W[:, i])

        if len(interference_terms) > 0:
            interference = cp.hstack(interference_terms)
            rhs = cp.norm(cp.hstack([interference, np.sqrt(sigma2)]))
        else:
            rhs = np.sqrt(sigma2)

        constraints.append(signal >= np.sqrt(gamma[k]) * rhs)

    constraints.append(cp.sum(cp.abs(W) ** 2) <= Pmax)

    problem = cp.Problem(cp.Minimize(0), constraints)

    problem.solve(solver=cp.SCS, verbose=False)

    feasible = problem.status in [cp.OPTIMAL, cp.OPTIMAL_INACCURATE]

    return feasible, W.value