# -*- coding: utf-8 -*-
"""Heuristic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18n3vajx39ZZxp3zkAvIEdqpkkFyvtJ_U
"""

import numpy as np


def functionHeuristicPowerAllocation(W, Pmax):
    """
    Equal power allocation heuristic
    """

    N, K = W.shape

    power_per_user = Pmax / K

    for k in range(K):
        W[:, k] = np.sqrt(power_per_user) * W[:, k] / np.linalg.norm(W[:, k])

    return W