# -*- coding: utf-8 -*-
"""MRT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZitECLwWxTkq1LQlcy4g0_YaQhjEgk4
"""

import numpy as np


def functionMRT(H, Pmax):
    """
    Maximum Ratio Transmission (MRT)

    Parameters
    ----------
    H : ndarray (N x K)
        Channel matrix
    Pmax : float
        Total transmit power

    Returns
    -------
    W : ndarray
        Beamforming matrix
    """

    N, K = H.shape

    W = np.zeros((N, K), dtype=complex)

    for k in range(K):
        hk = H[:, k]
        W[:, k] = hk / np.linalg.norm(hk)

    W = np.sqrt(Pmax / np.sum(np.abs(W) ** 2)) * W

    return W