# -*- coding: utf-8 -*-
"""simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-I5_Dtlhmub_of-4OzI21rp-LGRgdZp
"""

import numpy as np
import matplotlib.pyplot as plt

from mrt import functionMRT
from zfbf import functionZFBF
from slnrmax import functionSLNRMAX
from brb_algorithm import functionBRBalgorithm_cvx


np.random.seed(1)


N = 4
K = 4
Pmax = 10
sigma2 = 1


num_realizations = 100


mrt_rates = []
zf_rates = []
slnr_rates = []
optimal_rates = []


for realization in range(num_realizations):

    H = (
        np.random.randn(N, K)
        + 1j * np.random.randn(N, K)
    ) / np.sqrt(2)


    W_mrt = functionMRT(H, Pmax)
    W_zf = functionZFBF(H, Pmax)
    W_slnr = functionSLNRMAX(H, Pmax, sigma2)


    def compute_sum_rate(H, W, sigma2=1):

        K = H.shape[1]

        rates = []

        for k in range(K):

            hk = H[:, k]

            signal = np.abs(hk.conj().T @ W[:, k]) ** 2

            interference = 0

            for i in range(K):
                if i != k:
                    interference += np.abs(hk.conj().T @ W[:, i]) ** 2

            sinr = signal / (interference + sigma2)

            rates.append(np.log2(1 + sinr))

        return np.sum(rates)


    mrt_rates.append(compute_sum_rate(H, W_mrt, sigma2))
    zf_rates.append(compute_sum_rate(H, W_zf, sigma2))
    slnr_rates.append(compute_sum_rate(H, W_slnr, sigma2))


    optimal_rate, _ = functionBRBalgorithm_cvx(
        H,
        Pmax,
        sigma2
    )
plt.show()