# -*- coding: utf-8 -*-
"""slnrmax

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L66mE0c61hpZZgrIHZeA6rgC_K43U0O2
"""

import numpy as np
from scipy.linalg import eig


def functionSLNRMAX(H, Pmax, sigma2=1):
    """
    SLNR Maximization Beamforming
    """

    N, K = H.shape

    W = np.zeros((N, K), dtype=complex)

    for k in range(K):

        hk = H[:, k:k+1]

        interference = np.zeros((N, N), dtype=complex)

        for i in range(K):
            if i != k:
                hi = H[:, i:i+1]
                interference += hi @ hi.conj().T

        A = hk @ hk.conj().T
        B = interference + sigma2 * np.eye(N)

        eigvals, eigvecs = eig(A, B)

        idx = np.argmax(np.real(eigvals))

        wk = eigvecs[:, idx]

        W[:, k] = wk / np.linalg.norm(wk)

    W = np.sqrt(Pmax / np.sum(np.abs(W) ** 2)) * W

    return W