# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7rgiJEgMLWqPIdbXfI4Z-BQesqqQjax
"""

import numpy as np


def computeSINR(H, W, sigma2=1):

    K = H.shape[1]

    sinr = np.zeros(K)

    for k in range(K):

        hk = H[:, k]

        signal = np.abs(hk.conj().T @ W[:, k]) ** 2

        interference = 0

        for i in range(K):
            if i != k:
                interference += np.abs(hk.conj().T @ W[:, i]) ** 2

        sinr[k] = signal / (interference + sigma2)

    return sinr


def computeRate(H, W, sigma2=1):

    sinr = computeSINR(H, W, sigma2)

    return np.log2(1 + sinr)