# -*- coding: utf-8 -*-
"""ZFBF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14AsthiDNOhYRkjLHxElPy0zyTnbzCTE-
"""

import numpy as np


def functionZFBF(H, Pmax):
    """
    Zero Forcing Beamforming
    """

    Hh = H.conj().T

    W = H @ np.linalg.inv(Hh @ H)

    norms = np.linalg.norm(W, axis=0)
    W = W / norms

    W = np.sqrt(Pmax / np.sum(np.abs(W) ** 2)) * W

    return W